server:
  port: 8080
spring:
  application:
    name: planNUS
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: "change-me-please-at-least-256-bits-secret-change-me-please" # use env var in prod
    access-token-ttl-ms: 900000     # 15 minutes
    refresh-token-ttl-ms: 1209600000 # 14 days